'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { useRouter } from '@/i18n/routing';

type Item = { id: string; title: string; content: string; status: string; notifyMode: string; createdAt: string | number };
export default function AdminAnnouncementsPage() {
  const router = useRouter(); const [items, setItems] = useState<Item[]>([]); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [status, setStatus] = useState('draft'); const [notifyMode, setNotifyMode] = useState('silent');
  async function load() { const response = await fetch('/api/admin/announcements'); if (response.status === 401) { router.replace('/admin/login'); return; } if (response.ok) setItems((await response.json()).items); }
  useEffect(() => { load(); }, []);
  function start(item?: Item) { setFormOpen(true); setEditing(item || null); setTitle(item?.title || ''); setContent(item?.content || ''); setStatus(item?.status || 'draft'); setNotifyMode(item?.notifyMode || 'silent'); }
  async function save(event: FormEvent) { event.preventDefault(); const body = { title, content, status, notifyMode }; await fetch(editing ? `/api/admin/announcements/${editing.id}` : '/api/admin/announcements', { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); setFormOpen(false); setEditing(null); setTitle(''); setContent(''); await load(); }
  async function remove(id: string) { if (!confirm('Delete this announcement?')) return; await fetch(`/api/admin/announcements/${id}`, { method: 'DELETE' }); await load(); }
  return <main className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><h1 className="text-2xl font-semibold">Announcements</h1><Button onClick={() => start()}>New announcement</Button></div><div className="mt-6 space-y-3">{items.map((item) => <div key={item.id} className="flex items-center justify-between rounded-lg border bg-white p-4 dark:bg-zinc-900"><div><p className="font-medium">{item.title}</p><p className="text-xs text-zinc-500">{item.status} · {item.notifyMode}</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => start(item)}>Edit</Button><Button variant="outline" onClick={() => remove(item.id)}>Delete</Button></div></div>)}</div>{formOpen && <div className="fixed inset-0 z-50 flex items-start justify-center bg-black/40 p-4 pt-[8vh]"><form className="w-full max-w-2xl space-y-4 rounded-xl bg-white p-6 dark:bg-zinc-900" onSubmit={save}><h2 className="text-xl font-semibold">{editing ? 'Edit announcement' : 'New announcement'}</h2><Input required maxLength={200} placeholder="Title" value={title} onChange={(e) => setTitle(e.target.value)} /><Textarea required className="min-h-64 font-mono" placeholder="Markdown content" value={content} onChange={(e) => setContent(e.target.value)} /><div className="flex gap-3"><select className="rounded-md border px-3 py-2" value={status} onChange={(e) => setStatus(e.target.value)}><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select><select className="rounded-md border px-3 py-2" value={notifyMode} onChange={(e) => setNotifyMode(e.target.value)}><option value="silent">Silent</option><option value="popup">Popup</option></select></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setFormOpen(false)}>Cancel</Button><Button type="submit">Save</Button></div></form></div>}</main>;
}
